import { CardType } from './cardTypes'
import { Card } from '../features/cards/cardSlice'

const cardsData: Card[] = [
    // Attack Cards

    // Light Attacks
    {
        id: 1,
        name: 'Light Attack',
        action_type: CardType.Attack,
        description: 'An Attack Card reducing opponents defence or health',
        art: 'image',
        attack: 1,
        defense: 0,
        action_points: 1,
    },
    {
        id: 2,
        name: 'Light Attack',
        action_type: CardType.Attack,
        description: 'An Attack Card reducing opponents defence or health',
        art: 'image',
        attack: 1,
        defense: 0,
        action_points: 1,
    },
    {
        id: 3,
        name: 'Light Attack',
        action_type: CardType.Attack,
        description: 'An Attack Card reducing opponents defence or health',
        art: 'image',
        attack: 1,
        defense: 0,
        action_points: 1,
    },
    {
        id: 4,
        name: 'Light Attack',
        action_type: CardType.Attack,
        description: 'An Attack Card reducing opponents defence or health',
        art: 'image',
        attack: 1,
        defense: 0,
        action_points: 1,
    },
    {
        id: 5,
        name: 'Light Attack',
        action_type: CardType.Attack,
        description: 'An Attack Card reducing opponents defence or health',
        art: 'image',
        attack: 1,
        defense: 0,
        action_points: 1,
    },

    // Medium Attacks
    {
        id: 6,
        name: 'Medium Attack',
        action_type: CardType.Attack,
        description: 'An Attack Card reducing opponents defence or health',
        art: 'image',
        attack: 2,
        defense: 0,
        action_points: 2,
    },
    {
        id: 7,
        name: 'Medium Attack',
        action_type: CardType.Attack,
        description: 'An Attack Card reducing opponents defence or health',
        art: 'image',
        attack: 2,
        defense: 0,
        action_points: 2,
    },
    {
        id: 8,
        name: 'Medium Attack+',
        action_type: CardType.Attack,
        description: 'An Attack Card reducing opponents defence or health',
        art: 'image',
        attack: 2,
        defense: 0,
        action_points: 1,
    },

    // Heavy Attacks
    {
        id: 9,
        name: 'Heavy Attack',
        action_type: CardType.Attack,
        description: 'An Attack Card reducing opponents defence or health',
        art: 'image',
        attack: 3,
        defense: 0,
        action_points: 3,
    },
    {
        id: 10,
        name: 'Heavy Attack+',
        action_type: CardType.Attack,
        description: 'An Attack Card reducing opponents defence or health',
        art: 'image',
        attack: 3,
        defense: 0,
        action_points: 2,
    },

    // Defense Cards

    // Light Defense
    {
        id: 11,
        name: 'Light Defense',
        action_type: CardType.Defense,
        description: 'An Defense Card reducing opponents defence or health',
        art: 'image',
        attack: 0,
        defense: 1,
        action_points: 1,
    },
    {
        id: 12,
        name: 'Light Defense',
        action_type: CardType.Defense,
        description: 'An Defense Card reducing opponents defence or health',
        art: 'image',
        attack: 0,
        defense: 1,
        action_points: 1,
    },
    {
        id: 13,
        name: 'Light Defense',
        action_type: CardType.Defense,
        description: 'An Defense Card reducing opponents defence or health',
        art: 'image',
        attack: 0,
        defense: 1,
        action_points: 1,
    },
    {
        id: 14,
        name: 'Light Defense',
        action_type: CardType.Defense,
        description: 'An Defense Card reducing opponents defence or health',
        art: 'image',
        attack: 0,
        defense: 1,
        action_points: 1,
    },
    {
        id: 15,
        name: 'Light Defense',
        action_type: CardType.Defense,
        description: 'An Defense Card reducing opponents defence or health',
        art: 'image',
        attack: 0,
        defense: 1,
        action_points: 1,
    },

    // Medium Defense
    {
        id: 16,
        name: 'Medium Defense',
        action_type: CardType.Defense,
        description: 'An Defense Card reducing opponents defence or health',
        art: 'image',
        attack: 0,
        defense: 2,
        action_points: 2,
    },
    {
        id: 17,
        name: 'Medium Defense',
        action_type: CardType.Defense,
        description: 'An Defense Card reducing opponents defence or health',
        art: 'image',
        attack: 0,
        defense: 2,
        action_points: 2,
    },
    {
        id: 18,
        name: 'Medium Defense+',
        action_type: CardType.Defense,
        description: 'An Defense Card reducing opponents defence or health',
        art: 'image',
        attack: 0,
        defense: 2,
        action_points: 1,
    },

    // Heavy Attacks
    {
        id: 19,
        name: 'Heavy Defense',
        action_type: CardType.Defense,
        description: 'An Defense Card reducing opponents defence or health',
        art: 'image',
        attack: 0,
        defense: 3,
        action_points: 3,
    },
    {
        id: 20,
        name: 'Heavy Defense+',
        action_type: CardType.Defense,
        description: 'An Defense Card reducing opponents defence or health',
        art: 'image',
        attack: 0,
        defense: 3,
        action_points: 2,
    },

    // Buffs

    // Attack Buffs
    {
        id: 21,
        name: 'Attack Up',
        action_type: CardType.Buff,
        description: 'Adds 1 attack power to an Attack type card',
        art: 'image',
        attack: 1,
        defense: 0,
        action_points: 2,
    },
    {
        id: 22,
        name: 'Attack Up',
        action_type: CardType.Buff,
        description: 'Adds 1 attack power to an Attack type card',
        art: 'image',
        attack: 1,
        defense: 0,
        action_points: 2,
    },
    {
        id: 23,
        name: 'Attack Up',
        action_type: CardType.Buff,
        description: 'Adds 1 attack power to an Attack type card',
        art: 'image',
        attack: 1,
        defense: 0,
        action_points: 2,
    },
    {
        id: 24,
        name: 'Attack Up',
        action_type: CardType.Buff,
        description: 'Adds 1 attack power to an Attack type card',
        art: 'image',
        attack: 1,
        defense: 0,
        action_points: 2,
    },
    {
        id: 25,
        name: 'Attack Up+',
        action_type: CardType.Buff,
        description: 'Adds 2 attack power to an Attack type card',
        art: 'image',
        attack: 2,
        defense: 0,
        action_points: 1,
    },

    // Defense Buffs
    {
        id: 26,
        name: 'Defense Up',
        action_type: CardType.Buff,
        description: 'Adds 1 block to a Defense type card',
        art: 'image',
        attack: 0,
        defense: 1,
        action_points: 2,
    },
    {
        id: 27,
        name: 'Defense Up',
        action_type: CardType.Buff,
        description: 'Adds 1 block to a Defense type card',
        art: 'image',
        attack: 0,
        defense: 1,
        action_points: 2,
    },
    {
        id: 28,
        name: 'Defense Up',
        action_type: CardType.Buff,
        description: 'Adds 1 block to a Defense type card',
        art: 'image',
        attack: 0,
        defense: 1,
        action_points: 2,
    },
    {
        id: 29,
        name: 'Defense Up',
        action_type: CardType.Buff,
        description: 'Adds 2 block to a Defense type card',
        art: 'image',
        attack: 0,
        defense: 1,
        action_points: 2,
    },
    {
        id: 30,
        name: 'Defense Up+',
        action_type: CardType.Buff,
        description: 'Adds 2 block to a Defense type card',
        art: 'image',
        attack: 0,
        defense: 2,
        action_points: 1,
    },

    // Heals
    {
        id: 31,
        name: 'Heal',
        action_type: CardType.Heal,
        description: 'Adds 2 to Players Health',
        art: 'image',
        attack: 0,
        defense: 0,
        action_points: 2,
    },
    {
        id: 32,
        name: 'Heal',
        action_type: CardType.Heal,
        description: 'Adds 2 to Players Health',
        art: 'image',
        attack: 0,
        defense: 0,
        action_points: 2,
    },
    {
        id: 33,
        name: 'Heal',
        action_type: CardType.Heal,
        description: 'Adds 2 to Players Health',
        art: 'image',
        attack: 0,
        defense: 0,
        action_points: 2,
    },
    {
        id: 34,
        name: 'Heal',
        action_type: CardType.Heal,
        description: 'Adds 2 to Players Health',
        art: 'image',
        attack: 0,
        defense: 0,
        action_points: 2,
    },
    {
        id: 35,
        name: 'Heal+',
        action_type: CardType.Heal,
        description: 'Adds 5 to Players Health',
        art: 'image',
        attack: 0,
        defense: 0,
        action_points: 2,
    },

    // Action Points
    {
        id: 36,
        name: 'Action Points',
        action_type: CardType.Buff,
        description: 'Adds 1 to Players Action Points',
        art: 'image',
        attack: 0,
        defense: 0,
        action_points: 0,
    },
    {
        id: 37,
        name: 'Action Points',
        action_type: CardType.Buff,
        description: 'Adds 1 to Players Action Points',
        art: 'image',
        attack: 0,
        defense: 0,
        action_points: 0,
    },
    {
        id: 38,
        name: 'Action Points',
        action_type: CardType.Buff,
        description: 'Adds 1 to Players Action Points',
        art: 'image',
        attack: 0,
        defense: 0,
        action_points: 0,
    },
    {
        id: 39,
        name: 'Action Points',
        action_type: CardType.Buff,
        description: 'Adds 1 to Players Action Points',
        art: 'image',
        attack: 0,
        defense: 0,
        action_points: 0,
    },
    {
        id: 40,
        name: 'Action Points',
        action_type: CardType.Buff,
        description: 'Adds 1 to Players Action Points',
        art: 'image',
        attack: 0,
        defense: 0,
        action_points: 0,
    },
]

export default cardsData
